"""Database update

Revision ID: 0053cfd74ac2
Revises: 5a759e71753d
Create Date: 2025-05-11 09:33:50.770125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0053cfd74ac2'
down_revision = '5a759e71753d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
