"""Додано поле last_seen до user

Revision ID: 024b473d3825
Revises: 0053cfd74ac2
Create Date: 2025-05-11 10:14:59.683296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024b473d3825'
down_revision = '0053cfd74ac2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_path', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('original_file_name', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('mime_type', sa.String(), nullable=True))
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('messages', 'mime_type')
    op.drop_column('messages', 'original_file_name')
    op.drop_column('messages', 'file_path')
    # ### end Alembic commands ###
