"""Правки

Revision ID: 627bc93ae592
Revises: e8c8d53557c3
Create Date: 2025-05-13 20:35:30.418738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627bc93ae592'
down_revision = 'e8c8d53557c3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
