"""Smth new

Revision ID: b0048132fce7
Revises: eb556f4df19e
Create Date: 2025-05-15 10:57:27.164253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0048132fce7'
down_revision = 'eb556f4df19e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
