"""New one

Revision ID: c954b02a0429
Revises: b0048132fce7
Create Date: 2025-05-15 11:33:46.906915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c954b02a0429'
down_revision = 'b0048132fce7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('updated_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('messages', sa.Column('is_edited', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_edited')
    op.drop_column('messages', 'updated_at')
    # ### end Alembic commands ###
