"""empty message

Revision ID: eb556f4df19e
Revises: 627bc93ae592
Create Date: 2025-05-15 10:56:55.600112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb556f4df19e'
down_revision = '627bc93ae592'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('user1_last_typing_at', sa.TIMESTAMP(), nullable=True))
    op.add_column('chats', sa.Column('user2_last_typing_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'user2_last_typing_at')
    op.drop_column('chats', 'user1_last_typing_at')
    # ### end Alembic commands ###
