"""Database creation

Revision ID: ffb3552f0232
Revises: 459fce5f6e73
Create Date: 2025-04-02 16:50:56.697879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb3552f0232'
down_revision = '459fce5f6e73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
